def dice_help():
    print("Help:")
    print("")
    print("To roll a die, you simply need to tell me how many, and what kind.")
    print("This will be in the syntax of: #d#")
    print("...where the first # is how many (an integer) and the second # is what kind (also an integer).")
    print('Both numbers should be positive (no leading "-")')
    print("Example: 1d20 will roll one dice with 20 sides")
    print("")
    print("You can also add modifiers to rolls!")
    print("Example: 2d6+m2 will roll two dice with 6 sides, then add 2 to the total.")
    print("Alternatively: 3d6+e1 will roll three dice with 6 sides and add 1 to EACH roll.")
    print("")
    print("You can chain together multiple rolls in one go, too!")
    print('"1d20 2d4+e1 1d6" will roll 1d20, two d4s (adding 1 to each roll), and 1d6 and all them all up!')
    print("Or if you want to get crazy:")
    print('1d100 4d4+m5+e2 2d8+m-3')
    print("")
    print('Lastly, if the last thing you enter is " +t#" (where # is an integer)...')
    print('...that will add that much to the total of all the rolls')
    print('Example: "4d4 2d6 1d100 +t4"')
    print("")
    print("When you're all done, just type {}".format('"quit"'))
    print("Or type {} for other small quirks!".format('"help 2"'))
    print("")
