def dice_help_two():
    print("Help: The Other Page")
    print("")
    print("There are some small things you can do, as well.")
    print("")
    print("First, dice here are just numbers, so any unconventionally-sided die can be rolled.")
    print("So theoretically you could roll a 1 sided die.")
    print("...or a 75 sided die.")
    print("...or a 1000 sided die.")
    print("You get the idea.")
    print("")
    print('If you prefer the 10-sided dice combo (the d10 and a d00, or "percentile dice")')
    print("You can enable adding one to the d00 rolls. Oh, there's a d00. Fun fact.")
    print('just type "00 mode" by itself to enable this mode. You can turn it off by typing "00 mode" again.')
    print("")
    print("There's also a {} mode if you need that. Just type {}.".format('"coinflip"', '"coinflip"'))
    print("")
    print("And finally, there's a {} command, if you care about that.".format('"credits"'))
    print("")
